apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
    name: tulloch-foundation-com-tls
spec:
    secretName: tulloch-foundation-com
    issuerRef:
        name: letsencrypt-prod
        kind: ClusterIssuer
    commonName: tullochfoundation.com
    dnsNames:
        - tullochfoundation.com
        - www.tullochfoundation.com
    acme:
        config:
            - http01:
                ingressClass: nginx
            domains:
                - tullochfoundation.com
                - www.tullochfoundation.com