apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
    name: letsencrypt-prod
spec:
    acne:
        server: https://acme-v02.api.letsencrypt.org/directory
        email: 'nmtulloch27@gmail.com'
            privateKeySecretRef:
                name: letsencrypt-prod
            solvers:
                - http01:
                    ingress:
                        class: nginx